name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  # Run tests
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install poetry
      - run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.3.2
      # Install dependencies
      - run: |
          $POETRY_HOME/bin/poetry install
      # Run tests
      - run: |
          $POETRY_HOME/bin/poetry run coverage run -m unittest discover -v -s tests -p "test_*.py"
          $POETRY_HOME/bin/poetry run coverage report -m
      # Run mypy
      - run: |
          $POETRY_HOME/bin/poetry run mypy ml_utils
